Se va a crear un dataFrame donde poder extraer toda la información que se tiene de las competiciones de la plataforma Kaggle

In [1]:
import pandas as pd

### Completando los datos aportados:

Simplemente añadir a los datos de partida el Score de LeaderBoard Public

#### Importacion de los datosPartida

In [2]:
%cd C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\datosPartidaReady

datosPartidaReady = pd.read_csv("datosPartidaReady.csv", index_col = 0)
datosPartidaReady.head()

C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\datosPartidaReady

,competitionId,competitionTitle,deadline,evaluationMetric,hostSegment,rewardQuantity,totalKernels,totalTeams,change,entries,lastSubmission,rank,score,teamMembers,teamName
0,6004,Data Science Bowl 2017,2017-04-12T23:59:00Z,Multi-class logarithmic loss (logloss),featured,1000000,0.0,1972.0,136.0,2,2017-04-12T15:29:06.7133333Z,1.0,0.39975,"[{'profileUrl': '/badrobot', 'thumbnailUrl': '...",grt123
1,6004,Data Science Bowl 2017,2017-04-12T23:59:00Z,Multi-class logarithmic loss (logloss),featured,1000000,0.0,1972.0,87.0,2,2017-04-10T15:50:10.5066667Z,2.0,0.40117,"[{'profileUrl': '/dhammack', 'thumbnailUrl': '...",Julian de Wit & Daniel Hammack
2,6004,Data Science Bowl 2017,2017-04-12T23:59:00Z,Multi-class logarithmic loss (logloss),featured,1000000,0.0,1972.0,23.0,2,2017-04-11T14:59:55.6166667Z,3.0,0.40127,"[{'profileUrl': '/timsalimans', 'thumbnailUrl'...",Aidence
3,6004,Data Science Bowl 2017,2017-04-12T23:59:00Z,Multi-class logarithmic loss (logloss),featured,1000000,0.0,1972.0,157.0,3,2017-04-09T08:32:27.7366667Z,4.0,0.40183,"[{'profileUrl': '/jdingpku', 'thumbnailUrl': '...",qfpxfd
4,6004,Data Science Bowl 2017,2017-04-12T23:59:00Z,Multi-class logarithmic loss (logloss),featured,1000000,0.0,1972.0,349.0,8,2017-04-12T13:59:14.57Z,5.0,0.40409,"[{'profileUrl': '/pfillard', 'thumbnailUrl': '...",Pierre Fillard (Therapixel)

#### Importacion DatosLeaderBoardPublic

In [3]:
%cd C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\publicReady

LeaderBoardPublicReady = pd.read_csv("leaderboardPublicReady.csv", index_col = 0)
LeaderBoardPublicReady.head()

C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\publicReady

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

   teamName  publicScore  competitionId
0    Jim932      0.69607           4347
1     Mathn      0.69607           4347
2     Mathn      0.74705           4347
3     NxGTR      0.49468           4347
4  oconnoda      0.59338           4347

In [4]:
datosPartidacompleted = pd.merge(LeaderBoardPublicReady, datosPartidaReady, how = "inner", on = ["competitionId","teamName"])
datosPartidacompleted.head()

,teamName,publicScore,competitionId,competitionTitle,deadline,evaluationMetric,hostSegment,rewardQuantity,totalKernels,totalTeams,change,entries,lastSubmission,rank,score,teamMembers
0,pim#,0.50859,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,NaN,featured,30000,0.0,952.0,-21.0,140,2014-07-11T19:29:44.5233333Z,138.0,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '..."
1,pim#,0.56328,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,NaN,featured,30000,0.0,952.0,-21.0,140,2014-07-11T19:29:44.5233333Z,138.0,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '..."
2,pim#,0.56719,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,NaN,featured,30000,0.0,952.0,-21.0,140,2014-07-11T19:29:44.5233333Z,138.0,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '..."
3,pim#,0.57445,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,NaN,featured,30000,0.0,952.0,-21.0,140,2014-07-11T19:29:44.5233333Z,138.0,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '..."
4,pim#,0.58086,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,NaN,featured,30000,0.0,952.0,-21.0,140,2014-07-11T19:29:44.5233333Z,138.0,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '..."

In [5]:
print(len(datosPartidaReady.competitionTitle.unique()))
print(len(datosPartidacompleted.competitionTitle.unique()))

147
141

In [6]:
List_CompetitionsPartida_idcompetition = list(datosPartidaReady.competitionId)
List_datosPartidacompleted_idcompetition = list(datosPartidacompleted.competitionId)

Idcompetitions_lost = list(set(List_CompetitionsPartida_idcompetition) - set(List_datosPartidacompleted_idcompetition))
Idcompetitions_lost

[6565, 7878, 2408, 2442, 5874, 6322]

* Tener en cuanta estos 6 Dataframes y ver porque se pierden

### Completando los datos Scrapeados:

Se completa el dataFrame LeaderBoardPrivate con los datos de Competitions Scrapeados y LeaderBoardPublic.

In [8]:
%cd C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\privateReady

LeaderBoardPrivateReady = pd.read_csv("leaderboardPrivateReady.csv", index_col = 0)
LeaderBoardPrivateReady.head()

C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\privateReady

,evaluationMetric,entries,date,teamName,rank,score,teamMembers,competitionTitle,change
0,Mean Columnwise Root Mean Squared Error,6,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,Yasser Tabandeh,1,0.46892,"[{'name': 'Yasser Tabandeh', 'tier': 'grandmas...",Africa Soil Property Prediction Challenge,13
1,Mean Columnwise Root Mean Squared Error,14,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,Charly B.,2,0.46916,"[{'name': 'Charly B.', 'tier': 'master tier'}]",Africa Soil Property Prediction Challenge,427
2,Mean Columnwise Root Mean Squared Error,57,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,CodiLime.com,3,0.47016,"[{'name': 'Iwan Groźny', 'tier': 'master tier'...",Africa Soil Property Prediction Challenge,39
3,Mean Columnwise Root Mean Squared Error,17,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,seewaters,4,0.47239,"[{'name': 'seewaters', 'tier': 'master tier'}]",Africa Soil Property Prediction Challenge,57
4,Mean Columnwise Root Mean Squared Error,121,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,UK calling Africa,5,0.47637,"[{'name': 'Bluefool', 'tier': 'grandmaster tie...",Africa Soil Property Prediction Challenge,84

In [9]:
# Impotarcion del dataFrame Competitions Scrapeado
%cd C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\competitionsReady

competitionsReady = pd.read_csv("competitionsReady.csv", index_col = 0)
competitionsReady.head()

C:\Users\Usuario\Desktop\Kaggle\Data\dataFramesReady\competitionsReady

,lastSubmission,rewardQuantity,hostSegment,totalTeams,competitionTitle,competitionId
0,Sat Apr 04 2015 02:02:14 GMT+0200 (hora de ver...,Knowledge,Research,0,15.071x - The Analytics Edge (Spring 2015),4347
1,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015),4347
2,Thu Jan 17 2019 00:59:00 GMT+0100 (hora estánd...,Swag,Playground,142,20 Newsgroups Ciphertext Challenge,1213
3,Sat Nov 23 2013 00:59:00 GMT+0100 (hora estánd...,"$5,000",Research,633,Accelerometer Biometric Competition,3524
4,Sun Sep 30 2012 03:00:00 GMT+0200 (hora de ver...,"$1,000",Research,25,Data Mining Hackathon on BIG DATA (7GB) Best B...,3064

* total teams como sabemos hay que darle una vuelta o ponerle otro porque este no es el real...

### Union de dataFrames

In [10]:
PrivateReadyCompetitions = pd.merge(LeaderBoardPrivateReady, competitionsReady, how = "inner", on = ["competitionTitle"])
PrivateReadyCompetitions.head()

,evaluationMetric,entries,date,teamName,rank,score,teamMembers,competitionTitle,change,lastSubmission,rewardQuantity,hostSegment,totalTeams,competitionId
0,Mean Columnwise Root Mean Squared Error,6,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,Yasser Tabandeh,1,0.46892,"[{'name': 'Yasser Tabandeh', 'tier': 'grandmas...",Africa Soil Property Prediction Challenge,13,Wed Oct 22 2014 01:59:00 GMT+0200 (hora de ver...,"$8,000",Research,1233,3966
1,Mean Columnwise Root Mean Squared Error,14,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,Charly B.,2,0.46916,"[{'name': 'Charly B.', 'tier': 'master tier'}]",Africa Soil Property Prediction Challenge,427,Wed Oct 22 2014 01:59:00 GMT+0200 (hora de ver...,"$8,000",Research,1233,3966
2,Mean Columnwise Root Mean Squared Error,57,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,CodiLime.com,3,0.47016,"[{'name': 'Iwan Groźny', 'tier': 'master tier'...",Africa Soil Property Prediction Challenge,39,Wed Oct 22 2014 01:59:00 GMT+0200 (hora de ver...,"$8,000",Research,1233,3966
3,Mean Columnwise Root Mean Squared Error,17,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,seewaters,4,0.47239,"[{'name': 'seewaters', 'tier': 'master tier'}]",Africa Soil Property Prediction Challenge,57,Wed Oct 22 2014 01:59:00 GMT+0200 (hora de ver...,"$8,000",Research,1233,3966
4,Mean Columnwise Root Mean Squared Error,121,Wed Oct 22 2014 00:37:14 GMT+0200 (hora de ver...,UK calling Africa,5,0.47637,"[{'name': 'Bluefool', 'tier': 'grandmaster tie...",Africa Soil Property Prediction Challenge,84,Wed Oct 22 2014 01:59:00 GMT+0200 (hora de ver...,"$8,000",Research,1233,3966

In [11]:
len(PrivateReadyCompetitions.competitionTitle.unique())

59

In [12]:
PrivateReadyCompetitions.dtypes

evaluationMetric     object
entries               int64
date                 object
teamName             object
rank                  int64
score               float64
teamMembers          object
competitionTitle     object
change                int64
lastSubmission       object
rewardQuantity       object
hostSegment          object
totalTeams            int64
competitionId        object
dtype: object

In [13]:
PrivateReadyCompetitions['competitionId'] = PrivateReadyCompetitions['competitionId'].astype(float).astype(int)

In [14]:
PrivateReadyCompetitionscompleted = pd.merge(LeaderBoardPublicReady, PrivateReadyCompetitions, how = "inner", on = ["competitionId","teamName"])
PrivateReadyCompetitionscompleted.head()

,teamName,publicScore,competitionId,evaluationMetric,entries,date,rank,score,teamMembers,competitionTitle,change,lastSubmission,rewardQuantity,hostSegment,totalTeams
0,Oliver Nowak,0.14523,3080,Mean Average Precision at K,4,Sun Sep 30 2012 02:18:15 GMT+0200 (hora de ver...,80,0.14645,"[{'name': 'Oliver Nowak', 'tier': 'contributor...",Data Mining Hackathon on (20 mb) Best Buy mobi...,0,Sun Sep 30 2012 03:00:00 GMT+0200 (hora de ver...,$600,Research,96
1,Barry,0.00126,3080,Mean Average Precision at K,2,Sun Sep 30 2012 02:18:15 GMT+0200 (hora de ver...,81,0.14645,"[{'name': 'Barry', 'tier': 'contributor tier'}]",Data Mining Hackathon on (20 mb) Best Buy mobi...,0,Sun Sep 30 2012 03:00:00 GMT+0200 (hora de ver...,$600,Research,96
2,Barry,0.14523,3080,Mean Average Precision at K,2,Sun Sep 30 2012 02:18:15 GMT+0200 (hora de ver...,81,0.14645,"[{'name': 'Barry', 'tier': 'contributor tier'}]",Data Mining Hackathon on (20 mb) Best Buy mobi...,0,Sun Sep 30 2012 03:00:00 GMT+0200 (hora de ver...,$600,Research,96
3,InvincibleGuy,0.14523,3080,Mean Average Precision at K,1,Sun Sep 30 2012 02:18:15 GMT+0200 (hora de ver...,82,0.14645,"[{'name': 'Vikram Jha', 'tier': 'expert tier'}]",Data Mining Hackathon on (20 mb) Best Buy mobi...,0,Sun Sep 30 2012 03:00:00 GMT+0200 (hora de ver...,$600,Research,96
4,Shamus Patry,0.05509,3080,Mean Average Precision at K,15,Sun Sep 30 2012 02:18:15 GMT+0200 (hora de ver...,61,0.71217,"[{'name': 'Shamus Patry', 'tier': 'novice tier'}]",Data Mining Hackathon on (20 mb) Best Buy mobi...,-1,Sun Sep 30 2012 03:00:00 GMT+0200 (hora de ver...,$600,Research,96

In [15]:
len(PrivateReadyCompetitionscompleted.competitionTitle.unique())

59

In [16]:
PrivateReadyCompetitionscompleted.shape

(180577, 15)

In [17]:
datosPartidacompleted.shape

(724830, 16)

In [18]:
print(PrivateReadyCompetitionscompleted.columns)

Index(['teamName', 'publicScore', 'competitionId', 'evaluationMetric',
       'entries', 'date', 'rank', 'score', 'teamMembers', 'competitionTitle',
       'change', 'lastSubmission', 'rewardQuantity', 'hostSegment',
       'totalTeams'],
      dtype='object')

In [19]:
print(datosPartidacompleted.columns)

Index(['teamName', 'publicScore', 'competitionId', 'competitionTitle',
       'deadline', 'evaluationMetric', 'hostSegment', 'rewardQuantity',
       'totalKernels', 'totalTeams', 'change', 'entries', 'lastSubmission',
       'rank', 'score', 'teamMembers'],
      dtype='object')

In [20]:
datosPartidacompleted = datosPartidacompleted.drop(columns=["totalKernels"])

In [21]:
PrivateReadyCompetitionscompleted = PrivateReadyCompetitionscompleted.rename(columns = {"date":"deadline"})

In [22]:
dfKaggle = pd.concat([datosPartidacompleted,PrivateReadyCompetitionscompleted])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [23]:
dfKaggle

,change,competitionId,competitionTitle,deadline,entries,evaluationMetric,hostSegment,lastSubmission,publicScore,rank,rewardQuantity,score,teamMembers,teamName,totalTeams
0,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.50859,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
1,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.56328,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
2,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.56719,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
3,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.57445,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
4,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.58086,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
5,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.58683,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
6,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.58757,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
7,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.58897,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
8,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59000,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
9,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59082,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
10,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59303,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
11,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59354,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
12,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59428,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
13,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59540,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
14,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59593,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
15,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.59846,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
16,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.60373,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
17,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.60583,138.0,30000,0.59740,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
18,10.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,1,NaN,featured,2014-04-10T21:23:32.1233333Z,0.50000,849.0,30000,0.50000,"[{'profileUrl': '/abhichan', 'thumbnailUrl': '...",gradientDescent,952.0
19,2.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,14,NaN,featured,2014-07-13T17:50:39.6233333Z,0.50000,363.0,30000,0.58757,"[{'profileUrl': '/earino', 'thumbnailUrl': 'ht...",earino,952.0
20,2.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,14,NaN,featured,2014-07-13T17:50:39.6233333Z,0.56920,363.0,30000,0.58757,"[{'profileUrl': '/earino', 'thumbnailUrl': 'ht...",earino,952.0
21,2.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,14,NaN,featured,2014-07-13T17:50:39.6233333Z,0.56921,363.0,30000,0.58757,"[{'profileUrl': '/earino', 'thumbnailUrl': 'ht...",earino,952.0
22,2.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,14,NaN,featured,2014-07-13T17:50:39.6233333Z,0.56921,363.0,30000,0.58757,"[{'profileUrl': '/earino', 'thumbnailUrl': 'ht...",earino,952.0
23,2.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,14,NaN,featured,2014-07-13T17:50:39.6233333Z,0.59410,363.0,30000,0.58757,"[{'profileUrl': '/earino', 'thumbnailUrl': 'ht...",earino,952.0
24,-12.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,23,NaN,featured,2014-06-01T17:46:22.55Z,0.50000,382.0,30000,0.58735,"[{'profileUrl': '/piotrkuchta', 'thumbnailUrl'...",Piotr Kuchta,952.0
25,-12.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,23,NaN,featured,2014-06-01T17:46:22.55Z,0.53636,382.0,30000,0.58735,"[{'profileUrl': '/piotrkuchta', 'thumbnailUrl'...",Piotr Kuchta,952.0
26,-12.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,23,NaN,featured,2014-06-01T17:46:22.55Z,0.57057,382.0,30000,0.58735,"[{'profileUrl': '/piotrkuchta', 'thumbnailUrl'...",Piotr Kuchta,952.0
27,-12.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,23,NaN,featured,2014-06-01T17:46:22.55Z,0.57662,382.0,30000,0.58735,"[{'profileUrl': '/piotrkuchta', 'thumbnailUrl'...",Piotr Kuchta,952.0
28,-12.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,23,NaN,featured,2014-06-01T17:46:22.55Z,0.57847,382.0,30000,0.58735,"[{'profileUrl': '/piotrkuchta', 'thumbnailUrl'...",Piotr Kuchta,952.0
29,-12.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,23,NaN,featured,2014-06-01T17:46:22.55Z,0.59109,382.0,30000,0.58735,"[{'profileUrl': '/piotrkuchta', 'thumbnailUrl'...",Piotr Kuchta,952.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180547,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,40.21673,68.0,"$25,000",40.21673,"[{'name': 'Jose M.', 'tier': 'master tier'}]",Jose M.,1095.0
180548,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,40.31236,67.0,"$25,000",40.21613,"[{'name': 'Oscar Takeshita', 'tier': 'expert t...",Oscar Takeshita,1095.0
180549,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,40.21613,67.0,"$25,000",40.21613,"[{'name': 'Oscar Takeshita', 'tier': 'expert t...",Oscar Takeshita,1095.0
180550,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,36.89277,67.0,"$25,000",40.21613,"[{'name': 'Oscar Takeshita', 'tier': 'expert t...",Oscar Takeshita,1095.0
180551,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,47.11656,196.0,"$25,000",42.31461,"[{'name': 'Jasmine', 'tier': 'novice tier'}, {...",0.o,1095.0
180552,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,42.31461,196.0,"$25,000",42.31461,"[{'name': 'Jasmine', 'tier': 'novice tier'}, {...",0.o,1095.0
180553,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.31557,18.0,"$25,000",38.31557,"[{'name': 'Filipp Bykov', 'tier': 'novice tier'}]",Filipp Bykov,1095.0
180554,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.24273,18.0,"$25,000",38.31557,"[{'name': 'Filipp Bykov', 'tier': 'novice tier'}]",Filipp Bykov,1095.0
180555,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.14284,18.0,"$25,000",38.31557,"[{'name': 'Filipp Bykov', 'tier': 'novice tier'}]",Filipp Bykov,1095.0
180556,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.13648,18.0,"$25,000",38.31557,"[{'name': 'Filipp Bykov', 'tier': 'novice tier'}]",Filipp Bykov,1095.0
180557,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.08657,18.0,"$25,000",38.31557,"[{'name': 'Filipp Bykov', 'tier': 'novice tier'}]",Filipp Bykov,1095.0
180558,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.03532,18.0,"$25,000",38.31557,"[{'name': 'Filipp Bykov', 'tier': 'novice tier'}]",Filipp Bykov,1095.0
180559,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,40.58781,87.0,"$25,000",40.58781,"[{'name': 'Jack', 'tier': 'novice tier'}]",Jack,1095.0
180560,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,1,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,47.11656,298.0,"$25,000",47.11656,"[{'name': 'Arseny', 'tier': 'novice tier'}]",Arseny,1095.0
180561,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,45.68488,292.0,"$25,000",45.68488,"[{'name': 'gmobaz', 'tier': 'master tier'}]",gmobaz,1095.0
180562,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,35.48065,1.0,"$25,000",35.48065,"[{'name': 'Arthur Suilin', 'tier': 'expert tie...",Arthur Suilin,1095.0
180563,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,35.34648,1.0,"$25,000",35.48065,"[{'name': 'Arthur Suilin', 'tier': 'expert tie...",Arthur Suilin,1095.0
180564,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.58174,21.0,"$25,000",38.58174,"[{'name': 'slonoslon', 'tier': 'master tier'}]",slonoslon,1095.0
180565,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.75027,23.0,"$25,000",38.75027,"[{'name': 'MillCheck', 'tier': 'master tier'},...",deepsense.ai,1095.0
180566,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,57.07525,337.0,"$25,000",57.07525,"[{'name': 'Li-Der', 'tier': 'master tier'}]",Li-Der,1095.0
180567,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,129.67585,44.0,"$25,000",39.62840,"[{'name': 'Anvar Kodirov', 'tier': 'expert tie...",Anvar Kodirov,1095.0
180568,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,39.62840,44.0,"$25,000",39.62840,"[{'name': 'Anvar Kodirov', 'tier': 'expert tie...",Anvar Kodirov,1095.0
180569,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,41.94324,166.0,"$25,000",41.83956,"[{'name': 'Data Craze', 'tier': 'expert tier'}]",Wiki Walk,1095.0
180570,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,41.83956,166.0,"$25,000",41.83956,"[{'name': 'Data Craze', 'tier': 'expert tier'}]",Wiki Walk,1095.0
180571,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,46.08029,294.0,"$25,000",46.08029,"[{'name': 'Matt Thomson', 'tier': 'novice tier'}]",Matt Thomson,1095.0
180572,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,72.53636,347.0,"$25,000",72.53636,"[{'name': 'Ehsan', 'tier': 'expert tier'}]",Ehsan,1095.0
180573,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,38.39738,347.0,"$25,000",72.53636,"[{'name': 'Ehsan', 'tier': 'expert tier'}]",Ehsan,1095.0
180574,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,1,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,63.19908,341.0,"$25,000",63.19908,"[{'name': 'YuhuaXiong', 'tier': 'novice tier'}]",YuhuaXiong,1095.0
180575,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,2,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,41.46609,124.0,"$25,000",41.46609,"[{'name': 'KALE', 'tier': 'master tier'}]",KALE,1095.0
180576,0.0,6768,Web Traffic Time Series Forecasting,Tue Sep 12 2017 21:53:15 GMT+0200 (hora de ver...,1,SMAPE,Research,Thu Nov 16 2017 00:59:00 GMT+0100 (hora estánd...,37.61950,10.0,"$25,000",37.61950,"[{'name': 'Herra Huu', 'tier': 'grandmaster ti...",Herra Huu,1095.0

In [24]:
dfKaggle.shape

(905407, 15)

In [25]:
len(dfKaggle.competitionTitle.unique())

200

In [26]:
dfKaggle = dfKaggle.drop_duplicates()

In [36]:
dfKaggle.shape

(884977, 15)

### Completando con datos de otras competiciones

Completamos el dfKaggle con las competitiones que no tienen premio economico.

In [37]:
ListTotalCompetitions = list(LeaderBoardPublicReady.competitionId)

In [45]:
ListCompetitionReward = list(dfKaggle.competitionId)

In [46]:
competitionsNoReward = list(set(ListTotalCompetitions ) - set(ListCompetitionReward))

In [47]:
len(competitionsNoReward)

114

In [50]:
dfCompetitionNoReward = LeaderBoardPublicReady[LeaderBoardPublicReady["competitionId"].isin(competitionsNoReward)]

In [52]:
len(dfCompetitionNoReward.competitionId.unique())

114

In [56]:
dfCompetitionNoReward.dtypes

teamName          object
publicScore      float64
competitionId      int64
dtype: object

In [57]:
competitionsReady.dtypes

lastSubmission      object
rewardQuantity      object
hostSegment         object
totalTeams           int64
competitionTitle    object
competitionId       object
dtype: object

In [59]:
competitionsReady = competitionsReady[competitionsReady["competitionId"] != 'tart']
competitionsReady["competitionId"] = competitionsReady["competitionId"].astype(float).astype(int)

In [60]:
dfCompetitionNoReward_1 = pd.merge(dfCompetitionNoReward, competitionsReady, how = "inner", on = ["competitionId"])
dfCompetitionNoReward_1.head()

,teamName,publicScore,competitionId,lastSubmission,rewardQuantity,hostSegment,totalTeams,competitionTitle
0,Jim932,0.69607,4347,Sat Apr 04 2015 02:02:14 GMT+0200 (hora de ver...,Knowledge,Research,0,15.071x - The Analytics Edge (Spring 2015)
1,Jim932,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
2,Mathn,0.69607,4347,Sat Apr 04 2015 02:02:14 GMT+0200 (hora de ver...,Knowledge,Research,0,15.071x - The Analytics Edge (Spring 2015)
3,Mathn,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
4,Mathn,0.74705,4347,Sat Apr 04 2015 02:02:14 GMT+0200 (hora de ver...,Knowledge,Research,0,15.071x - The Analytics Edge (Spring 2015)

In [61]:
dfCompetitionNoReward_2 = dfCompetitionNoReward_1[dfCompetitionNoReward_1["totalTeams"] == 0]

In [62]:
len(dfCompetitionNoReward_2.competitionId.unique())

1

In [63]:
dfCompetitionNoReward_2 = dfCompetitionNoReward_1[dfCompetitionNoReward_1["totalTeams"] != 0]

In [64]:
dfCompetitionNoReward_2.drop_duplicates()

,teamName,publicScore,competitionId,lastSubmission,rewardQuantity,hostSegment,totalTeams,competitionTitle
1,Jim932,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
3,Mathn,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
5,Mathn,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
7,NxGTR,0.49468,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
9,oconnoda,0.59338,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
11,oconnoda,0.78511,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
13,Estelle,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
15,BarryPolley,0.49468,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
17,BarryPolley,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
19,BrianJL,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
21,BrianJL,0.74392,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
23,Jim932,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
25,Estelle,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
27,BrianJL,0.75910,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
29,BrianJL,0.77774,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
31,Gino,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
33,js,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
35,Mario,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
37,Saikiran,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
39,Mario,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
41,L. Youseff,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
43,Saikiran,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
45,mattglibota,0.78317,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
47,Halvard,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
49,Ryan Kuhn,0.50000,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
51,L. Youseff,0.70129,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
53,persona03,0.50000,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
55,egil137,0.86867,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
57,ErikO,0.90547,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
59,Revan,0.78317,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,Knowledge,Research,2923,15.071x - The Analytics Edge (Spring 2015)
...,...,...,...,...,...,...,...,...
403717,sumo,0.82757,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403718,y,0.82674,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403719,y,0.82742,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403720,Ambrotos,0.57424,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403721,Johannes Ahlmann,0.80280,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403722,EnGenius,0.63845,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403723,yagnesh revar,0.59944,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403724,RakeshKumar,0.78834,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403725,Ambrotos,0.61623,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403726,i wish i had a titan,0.80649,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403727,vgng,0.83022,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403728,yagnesh revar,0.60155,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403729,yagnesh revar,0.62359,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403730,yagnesh revar,0.62740,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403731,yagnesh revar,0.63057,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403732,yagnesh revar,0.63845,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403733,mani kanta,0.76469,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403734,Minnesota Sunshine,0.81342,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403735,Minnesota Sunshine,0.81600,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403736,André Muta,0.63790,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403737,Keiku,0.82679,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403738,tambuzi,0.79774,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403739,tambuzi,0.80123,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403740,Keiku,0.82691,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403741,Abi Rafdi,0.78134,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403742,14283,0.80416,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403743,Abi Rafdi,0.79633,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403744,Abi Rafdi,0.81030,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403745,ZepplinRules,0.76437,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification
403746,ZepplinRules,0.78896,4829,Wed Apr 13 2016 01:59:00 GMT+0200 (hora de ver...,Jobs,Recruitment,355,Yelp Restaurant Photo Classification

In [65]:
dfKaggle.columns

Index(['change', 'competitionId', 'competitionTitle', 'deadline', 'entries',
       'evaluationMetric', 'hostSegment', 'lastSubmission', 'publicScore',
       'rank', 'rewardQuantity', 'score', 'teamMembers', 'teamName',
       'totalTeams'],
      dtype='object')

In [87]:
dfCompetitionNoReward_2["change"] = None
dfCompetitionNoReward_2["deadline"] = None
dfCompetitionNoReward_2['rank'] = None
dfCompetitionNoReward_2['score'] = None
dfCompetitionNoReward_2['teamMembers'] = None
dfCompetitionNoReward_2['rewardQuantity'] = None
dfCompetitionNoReward_2['evaluationMetric'] = None

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [88]:
DtentriesNoreward= dfCompetitionNoReward_2.groupby('competitionId').agg({"competitionId":"count"})
DtentriesNoreward = DtentriesNoreward.rename(columns = {"competitionId" : "entries"})
DtentriesNoreward = DtentriesNoreward.reset_index()
DtentriesNoreward.head()

   competitionId  entries
0           1001    17886
1           1002     1385
2           1017     6746
3           1020     8368
4           1030     6052

In [89]:
dfCompetitionNoReward_3 = pd.merge(dfCompetitionNoReward_2, DtentriesNoreward, how = "inner", on = ["competitionId"])
dfCompetitionNoReward_3.head()

,teamName,publicScore,competitionId,lastSubmission,rewardQuantity,hostSegment,totalTeams,competitionTitle,change,deadline,rank,score,teamMembers,evaluationMetric,entries
0,Jim932,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
1,Mathn,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
2,Mathn,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
3,NxGTR,0.49468,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
4,oconnoda,0.59338,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465

In [93]:
dfKaggle.head()

,change,competitionId,competitionTitle,deadline,entries,evaluationMetric,hostSegment,lastSubmission,publicScore,rank,rewardQuantity,score,teamMembers,teamName,totalTeams
0,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.50859,138.0,30000,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
1,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.56328,138.0,30000,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
2,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.56719,138.0,30000,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
3,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.57445,138.0,30000,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0
4,-21.0,3897,Acquire Valued Shoppers Challenge,2014-07-14T23:59:00Z,140,NaN,featured,2014-07-11T19:29:44.5233333Z,0.58086,138.0,30000,0.5974,"[{'profileUrl': '/spimenov', 'thumbnailUrl': '...",pim#,952.0

In [94]:
dfCompetitionNoReward_3.head()

,teamName,publicScore,competitionId,lastSubmission,rewardQuantity,hostSegment,totalTeams,competitionTitle,change,deadline,rank,score,teamMembers,evaluationMetric,entries
0,Jim932,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
1,Mathn,0.69607,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
2,Mathn,0.74705,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
3,NxGTR,0.49468,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465
4,oconnoda,0.59338,4347,Tue May 05 2015 01:59:00 GMT+0200 (hora de ver...,None,Research,2923,15.071x - The Analytics Edge (Spring 2015),None,None,None,None,None,None,13465

In [98]:
dfKaggle = dfKaggle.where(dfKaggle.notnull(), dfKaggle.astype(str))
dfCompetitionNoReward_3 = dfCompetitionNoReward_3.where(dfCompetitionNoReward_3.notnull(), dfCompetitionNoReward_3.astype(str))

dfKaggleCompleted = pd.concat([dfKaggle,dfCompetitionNoReward_3])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.

In [99]:
len(dfKaggleCompleted.competitionId.unique())

308

In [101]:
%cd C:\Users\Usuario\Desktop\Kaggle\Data
dfKaggleCompleted.to_csv("dfKaggleCompleted.csv")

C:\Users\Usuario\Desktop\Kaggle\Data